spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

keycloak.realm=${KEYCLOAK_REALM}
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://Keycloak:8080/realms/${keycloak.realm}
